base_url = "https://danielabellan.github.io/"
title = "Daniel Abellán-Vázquez"
theme = "serene"
default_language = "es"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
author        = "Daniel Abellán-Vázquez"
bio           = "Economista y traductor. Opositor al Cuerpo Superior de Técnicos Comerciales del Estado."
avatar        = "avatar.jpg"

# Ajustes del tema
force_theme        = ""          # "" | "light" | "dark"
theme_switcher     = true
not_found_error_text = "No se encontró la página."
not_found_home_text  = "Volver al inicio"

# Redes
linkedin  = "danielabellanv"
x         = "danielabellanv"
instagram = "danielabellanv"
