base_url = "https://danielabellan.github.io/"
title = "Daniel Abellán-Vázquez"
theme = "serene"
default_language = "es"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
author   = "Daniel Abellán-Vázquez"
bio      = "Economista y traductor. Opositor al Cuerpo Superior de Técnicos Comerciales del Estado."
avatar   = "avatar.jpg"      # pon tu foto en /static con este nombre

# —— Ajustes del tema ——
# Deja "" para respetar el modo del sistema; usa "light" o "dark" para forzar.
force_theme   = ""
theme_switcher = true

# Redes
linkedin  = "danielabellanv"
x         = "danielabellanv"
instagram = "danielabellanv"
